'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WSISTKGZ
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSISTKGZ.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IzvrsiSQLvratiDT", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function IzvrsiSQLvratiDT(ByVal sql As String, ByVal connPravaBaza As String, ByVal lang As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IzvrsiSQLvratiDT", ReplyAction:="*")>  _
        Function IzvrsiSQLvratiDTAsync(ByVal sql As String, ByVal connPravaBaza As String, ByVal lang As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IzvrsiSQL", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function IzvrsiSQL(ByVal sql As String, ByVal connPravaBaza As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IzvrsiSQL", ReplyAction:="*")>  _
        Function IzvrsiSQLAsync(ByVal sql As String, ByVal connPravaBaza As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IzvrsiSQLVratiBrojSlogova", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function IzvrsiSQLVratiBrojSlogova(ByVal sql As String, ByVal connPravaBaza As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IzvrsiSQLVratiBrojSlogova", ReplyAction:="*")>  _
        Function IzvrsiSQLVratiBrojSlogovaAsync(ByVal sql As String, ByVal connPravaBaza As String) As System.Threading.Tasks.Task(Of Integer)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits WSISTKGZ.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSISTKGZ.ServiceSoap)
        Implements WSISTKGZ.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function IzvrsiSQLvratiDT(ByVal sql As String, ByVal connPravaBaza As String, ByVal lang As String) As System.Data.DataSet Implements WSISTKGZ.ServiceSoap.IzvrsiSQLvratiDT
            Return MyBase.Channel.IzvrsiSQLvratiDT(sql, connPravaBaza, lang)
        End Function
        
        Public Function IzvrsiSQLvratiDTAsync(ByVal sql As String, ByVal connPravaBaza As String, ByVal lang As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WSISTKGZ.ServiceSoap.IzvrsiSQLvratiDTAsync
            Return MyBase.Channel.IzvrsiSQLvratiDTAsync(sql, connPravaBaza, lang)
        End Function
        
        Public Function IzvrsiSQL(ByVal sql As String, ByVal connPravaBaza As String) As String Implements WSISTKGZ.ServiceSoap.IzvrsiSQL
            Return MyBase.Channel.IzvrsiSQL(sql, connPravaBaza)
        End Function
        
        Public Function IzvrsiSQLAsync(ByVal sql As String, ByVal connPravaBaza As String) As System.Threading.Tasks.Task(Of String) Implements WSISTKGZ.ServiceSoap.IzvrsiSQLAsync
            Return MyBase.Channel.IzvrsiSQLAsync(sql, connPravaBaza)
        End Function
        
        Public Function IzvrsiSQLVratiBrojSlogova(ByVal sql As String, ByVal connPravaBaza As String) As Integer Implements WSISTKGZ.ServiceSoap.IzvrsiSQLVratiBrojSlogova
            Return MyBase.Channel.IzvrsiSQLVratiBrojSlogova(sql, connPravaBaza)
        End Function
        
        Public Function IzvrsiSQLVratiBrojSlogovaAsync(ByVal sql As String, ByVal connPravaBaza As String) As System.Threading.Tasks.Task(Of Integer) Implements WSISTKGZ.ServiceSoap.IzvrsiSQLVratiBrojSlogovaAsync
            Return MyBase.Channel.IzvrsiSQLVratiBrojSlogovaAsync(sql, connPravaBaza)
        End Function
    End Class
End Namespace
