<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tns="http://tempuri.org/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:element name="AutentifikacijaKorisnika_IzTabele_StoreProcedure">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Nalog" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Lozinka_Flat" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="ImeSP" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AutentifikacijaKorisnika_IzTabele_StoreProcedureResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="AutentifikacijaKorisnika_IzTabele_StoreProcedureResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IzmenaLozinke_WebAPP">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Nalog" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Lozinka_Flat" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="ImeSP" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IzmenaLozinke_WebAPPResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="IzmenaLozinke_WebAPPResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DajDS_IzUpita">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Upit" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DajDS_IzUpitaResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="DajDS_IzUpitaResult">
              <s:complexType>
                <s:sequence>
                  <s:element ref="s:schema" />
                  <s:any />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DajDS_SP">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ImeSP" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Parametri" type="tns:ArrayOfAnyType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfAnyType">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="anyType" nillable="true" />
        </s:sequence>
      </s:complexType>
      <s:element name="DajDS_SPResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="DajDS_SPResult">
              <s:complexType>
                <s:sequence>
                  <s:element ref="s:schema" />
                  <s:any />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DajScalarSTR_SP">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ImeSP" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Parametri" type="tns:ArrayOfAnyType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DajScalarSTR_SPResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="DajScalarSTR_SPResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SP_ExecuteNonQuery">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ImeSP" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Parametri" type="tns:ArrayOfAnyType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="SP_ExecuteNonQueryResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="SP_ExecuteNonQueryResult" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpisPromenaBrisanje_SP">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ImeSP" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="Parametri" type="tns:ArrayOfAnyType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpisPromenaBrisanje_SPResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="UpisPromenaBrisanje_SPResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpisPromenaBrisanje_IzUpita">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Upit" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpisPromenaBrisanje_IzUpitaResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="UpisPromenaBrisanje_IzUpitaResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpisPromenaBrisanje">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Upit" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpisPromenaBrisanjeResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="UpisPromenaBrisanjeResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpisVratiID">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Upit" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="UpisVratiIDResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="UpisVratiIDResult" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ProveraFormataBrojaTelefona">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="BrojTelefona" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ProveraFormataBrojaTelefonaResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="ProveraFormataBrojaTelefonaResult" type="s:short" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ProveraFormataBrojaTelefona_MinDuzina">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="BrojTelefona" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="MinDuzinaBroja" type="s:short" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ProveraFormataBrojaTelefona_MinDuzinaResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="ProveraFormataBrojaTelefona_MinDuzinaResult" type="s:short" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IsValidEmailFormat">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputEmail" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IsValidEmailFormatResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="IsValidEmailFormatResult" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IsValidURL">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="inputURL" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IsValidURLResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="IsValidURLResult" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IsValid_TekstPolje">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="TekstPolja" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="minDuzina" type="s:short" />
            <s:element minOccurs="1" maxOccurs="1" name="maxDuzina" type="s:short" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IsValid_TekstPoljeResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="IsValid_TekstPoljeResult" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IsValidIPAddress">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="strIPAddress" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IsValidIPAddressResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="IsValidIPAddressResult" type="s:boolean" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="Provera_Po_MOD11">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="mbr" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="Provera_Po_MOD11Response">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Provera_Po_MOD11Result" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DajScalarSTR_IzUpita">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="Upit" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="konekcija" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="DajScalarSTR_IzUpitaResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="DajScalarSTR_IzUpitaResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IzvrsiSQLvratiDT">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="sql" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="connPravaBaza" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="lang" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IzvrsiSQLvratiDTResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IzvrsiSQLvratiDTResult">
              <s:complexType>
                <s:sequence>
                  <s:element ref="s:schema" />
                  <s:any />
                </s:sequence>
              </s:complexType>
            </s:element>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IzvrsiSQL">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="sql" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="connPravaBaza" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IzvrsiSQLResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="IzvrsiSQLResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IzvrsiSQLVratiBrojSlogova">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="sql" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="connPravaBaza" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="IzvrsiSQLVratiBrojSlogovaResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="IzvrsiSQLVratiBrojSlogovaResult" type="s:int" />
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="AutentifikacijaKorisnika_IzTabele_StoreProcedureSoapIn">
    <wsdl:part name="parameters" element="tns:AutentifikacijaKorisnika_IzTabele_StoreProcedure" />
  </wsdl:message>
  <wsdl:message name="AutentifikacijaKorisnika_IzTabele_StoreProcedureSoapOut">
    <wsdl:part name="parameters" element="tns:AutentifikacijaKorisnika_IzTabele_StoreProcedureResponse" />
  </wsdl:message>
  <wsdl:message name="IzmenaLozinke_WebAPPSoapIn">
    <wsdl:part name="parameters" element="tns:IzmenaLozinke_WebAPP" />
  </wsdl:message>
  <wsdl:message name="IzmenaLozinke_WebAPPSoapOut">
    <wsdl:part name="parameters" element="tns:IzmenaLozinke_WebAPPResponse" />
  </wsdl:message>
  <wsdl:message name="DajDS_IzUpitaSoapIn">
    <wsdl:part name="parameters" element="tns:DajDS_IzUpita" />
  </wsdl:message>
  <wsdl:message name="DajDS_IzUpitaSoapOut">
    <wsdl:part name="parameters" element="tns:DajDS_IzUpitaResponse" />
  </wsdl:message>
  <wsdl:message name="DajDS_SPSoapIn">
    <wsdl:part name="parameters" element="tns:DajDS_SP" />
  </wsdl:message>
  <wsdl:message name="DajDS_SPSoapOut">
    <wsdl:part name="parameters" element="tns:DajDS_SPResponse" />
  </wsdl:message>
  <wsdl:message name="DajScalarSTR_SPSoapIn">
    <wsdl:part name="parameters" element="tns:DajScalarSTR_SP" />
  </wsdl:message>
  <wsdl:message name="DajScalarSTR_SPSoapOut">
    <wsdl:part name="parameters" element="tns:DajScalarSTR_SPResponse" />
  </wsdl:message>
  <wsdl:message name="SP_ExecuteNonQuerySoapIn">
    <wsdl:part name="parameters" element="tns:SP_ExecuteNonQuery" />
  </wsdl:message>
  <wsdl:message name="SP_ExecuteNonQuerySoapOut">
    <wsdl:part name="parameters" element="tns:SP_ExecuteNonQueryResponse" />
  </wsdl:message>
  <wsdl:message name="UpisPromenaBrisanje_SPSoapIn">
    <wsdl:part name="parameters" element="tns:UpisPromenaBrisanje_SP" />
  </wsdl:message>
  <wsdl:message name="UpisPromenaBrisanje_SPSoapOut">
    <wsdl:part name="parameters" element="tns:UpisPromenaBrisanje_SPResponse" />
  </wsdl:message>
  <wsdl:message name="UpisPromenaBrisanje_IzUpitaSoapIn">
    <wsdl:part name="parameters" element="tns:UpisPromenaBrisanje_IzUpita" />
  </wsdl:message>
  <wsdl:message name="UpisPromenaBrisanje_IzUpitaSoapOut">
    <wsdl:part name="parameters" element="tns:UpisPromenaBrisanje_IzUpitaResponse" />
  </wsdl:message>
  <wsdl:message name="UpisPromenaBrisanjeSoapIn">
    <wsdl:part name="parameters" element="tns:UpisPromenaBrisanje" />
  </wsdl:message>
  <wsdl:message name="UpisPromenaBrisanjeSoapOut">
    <wsdl:part name="parameters" element="tns:UpisPromenaBrisanjeResponse" />
  </wsdl:message>
  <wsdl:message name="UpisVratiIDSoapIn">
    <wsdl:part name="parameters" element="tns:UpisVratiID" />
  </wsdl:message>
  <wsdl:message name="UpisVratiIDSoapOut">
    <wsdl:part name="parameters" element="tns:UpisVratiIDResponse" />
  </wsdl:message>
  <wsdl:message name="ProveraFormataBrojaTelefonaSoapIn">
    <wsdl:part name="parameters" element="tns:ProveraFormataBrojaTelefona" />
  </wsdl:message>
  <wsdl:message name="ProveraFormataBrojaTelefonaSoapOut">
    <wsdl:part name="parameters" element="tns:ProveraFormataBrojaTelefonaResponse" />
  </wsdl:message>
  <wsdl:message name="ProveraFormataBrojaTelefona_MinDuzinaSoapIn">
    <wsdl:part name="parameters" element="tns:ProveraFormataBrojaTelefona_MinDuzina" />
  </wsdl:message>
  <wsdl:message name="ProveraFormataBrojaTelefona_MinDuzinaSoapOut">
    <wsdl:part name="parameters" element="tns:ProveraFormataBrojaTelefona_MinDuzinaResponse" />
  </wsdl:message>
  <wsdl:message name="IsValidEmailFormatSoapIn">
    <wsdl:part name="parameters" element="tns:IsValidEmailFormat" />
  </wsdl:message>
  <wsdl:message name="IsValidEmailFormatSoapOut">
    <wsdl:part name="parameters" element="tns:IsValidEmailFormatResponse" />
  </wsdl:message>
  <wsdl:message name="IsValidURLSoapIn">
    <wsdl:part name="parameters" element="tns:IsValidURL" />
  </wsdl:message>
  <wsdl:message name="IsValidURLSoapOut">
    <wsdl:part name="parameters" element="tns:IsValidURLResponse" />
  </wsdl:message>
  <wsdl:message name="IsValid_TekstPoljeSoapIn">
    <wsdl:part name="parameters" element="tns:IsValid_TekstPolje" />
  </wsdl:message>
  <wsdl:message name="IsValid_TekstPoljeSoapOut">
    <wsdl:part name="parameters" element="tns:IsValid_TekstPoljeResponse" />
  </wsdl:message>
  <wsdl:message name="IsValidIPAddressSoapIn">
    <wsdl:part name="parameters" element="tns:IsValidIPAddress" />
  </wsdl:message>
  <wsdl:message name="IsValidIPAddressSoapOut">
    <wsdl:part name="parameters" element="tns:IsValidIPAddressResponse" />
  </wsdl:message>
  <wsdl:message name="Provera_Po_MOD11SoapIn">
    <wsdl:part name="parameters" element="tns:Provera_Po_MOD11" />
  </wsdl:message>
  <wsdl:message name="Provera_Po_MOD11SoapOut">
    <wsdl:part name="parameters" element="tns:Provera_Po_MOD11Response" />
  </wsdl:message>
  <wsdl:message name="DajScalarSTR_IzUpitaSoapIn">
    <wsdl:part name="parameters" element="tns:DajScalarSTR_IzUpita" />
  </wsdl:message>
  <wsdl:message name="DajScalarSTR_IzUpitaSoapOut">
    <wsdl:part name="parameters" element="tns:DajScalarSTR_IzUpitaResponse" />
  </wsdl:message>
  <wsdl:message name="IzvrsiSQLvratiDTSoapIn">
    <wsdl:part name="parameters" element="tns:IzvrsiSQLvratiDT" />
  </wsdl:message>
  <wsdl:message name="IzvrsiSQLvratiDTSoapOut">
    <wsdl:part name="parameters" element="tns:IzvrsiSQLvratiDTResponse" />
  </wsdl:message>
  <wsdl:message name="IzvrsiSQLSoapIn">
    <wsdl:part name="parameters" element="tns:IzvrsiSQL" />
  </wsdl:message>
  <wsdl:message name="IzvrsiSQLSoapOut">
    <wsdl:part name="parameters" element="tns:IzvrsiSQLResponse" />
  </wsdl:message>
  <wsdl:message name="IzvrsiSQLVratiBrojSlogovaSoapIn">
    <wsdl:part name="parameters" element="tns:IzvrsiSQLVratiBrojSlogova" />
  </wsdl:message>
  <wsdl:message name="IzvrsiSQLVratiBrojSlogovaSoapOut">
    <wsdl:part name="parameters" element="tns:IzvrsiSQLVratiBrojSlogovaResponse" />
  </wsdl:message>
  <wsdl:portType name="ServiceSoap">
    <wsdl:operation name="AutentifikacijaKorisnika_IzTabele_StoreProcedure">
      <wsdl:input message="tns:AutentifikacijaKorisnika_IzTabele_StoreProcedureSoapIn" />
      <wsdl:output message="tns:AutentifikacijaKorisnika_IzTabele_StoreProcedureSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IzmenaLozinke_WebAPP">
      <wsdl:input message="tns:IzmenaLozinke_WebAPPSoapIn" />
      <wsdl:output message="tns:IzmenaLozinke_WebAPPSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="DajDS_IzUpita">
      <wsdl:input message="tns:DajDS_IzUpitaSoapIn" />
      <wsdl:output message="tns:DajDS_IzUpitaSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="DajDS_SP">
      <wsdl:input message="tns:DajDS_SPSoapIn" />
      <wsdl:output message="tns:DajDS_SPSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="DajScalarSTR_SP">
      <wsdl:input message="tns:DajScalarSTR_SPSoapIn" />
      <wsdl:output message="tns:DajScalarSTR_SPSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="SP_ExecuteNonQuery">
      <wsdl:input message="tns:SP_ExecuteNonQuerySoapIn" />
      <wsdl:output message="tns:SP_ExecuteNonQuerySoapOut" />
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje_SP">
      <wsdl:input message="tns:UpisPromenaBrisanje_SPSoapIn" />
      <wsdl:output message="tns:UpisPromenaBrisanje_SPSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje_IzUpita">
      <wsdl:input message="tns:UpisPromenaBrisanje_IzUpitaSoapIn" />
      <wsdl:output message="tns:UpisPromenaBrisanje_IzUpitaSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje">
      <wsdl:input message="tns:UpisPromenaBrisanjeSoapIn" />
      <wsdl:output message="tns:UpisPromenaBrisanjeSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="UpisVratiID">
      <wsdl:input message="tns:UpisVratiIDSoapIn" />
      <wsdl:output message="tns:UpisVratiIDSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ProveraFormataBrojaTelefona">
      <wsdl:input message="tns:ProveraFormataBrojaTelefonaSoapIn" />
      <wsdl:output message="tns:ProveraFormataBrojaTelefonaSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="ProveraFormataBrojaTelefona_MinDuzina">
      <wsdl:input message="tns:ProveraFormataBrojaTelefona_MinDuzinaSoapIn" />
      <wsdl:output message="tns:ProveraFormataBrojaTelefona_MinDuzinaSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IsValidEmailFormat">
      <wsdl:input message="tns:IsValidEmailFormatSoapIn" />
      <wsdl:output message="tns:IsValidEmailFormatSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IsValidURL">
      <wsdl:input message="tns:IsValidURLSoapIn" />
      <wsdl:output message="tns:IsValidURLSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IsValid_TekstPolje">
      <wsdl:input message="tns:IsValid_TekstPoljeSoapIn" />
      <wsdl:output message="tns:IsValid_TekstPoljeSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IsValidIPAddress">
      <wsdl:input message="tns:IsValidIPAddressSoapIn" />
      <wsdl:output message="tns:IsValidIPAddressSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="Provera_Po_MOD11">
      <wsdl:input message="tns:Provera_Po_MOD11SoapIn" />
      <wsdl:output message="tns:Provera_Po_MOD11SoapOut" />
    </wsdl:operation>
    <wsdl:operation name="DajScalarSTR_IzUpita">
      <wsdl:input message="tns:DajScalarSTR_IzUpitaSoapIn" />
      <wsdl:output message="tns:DajScalarSTR_IzUpitaSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQLvratiDT">
      <wsdl:input message="tns:IzvrsiSQLvratiDTSoapIn" />
      <wsdl:output message="tns:IzvrsiSQLvratiDTSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQL">
      <wsdl:input message="tns:IzvrsiSQLSoapIn" />
      <wsdl:output message="tns:IzvrsiSQLSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQLVratiBrojSlogova">
      <wsdl:input message="tns:IzvrsiSQLVratiBrojSlogovaSoapIn" />
      <wsdl:output message="tns:IzvrsiSQLVratiBrojSlogovaSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServiceSoap" type="tns:ServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="AutentifikacijaKorisnika_IzTabele_StoreProcedure">
      <soap:operation soapAction="http://tempuri.org/AutentifikacijaKorisnika_IzTabele_StoreProcedure" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IzmenaLozinke_WebAPP">
      <soap:operation soapAction="http://tempuri.org/IzmenaLozinke_WebAPP" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DajDS_IzUpita">
      <soap:operation soapAction="http://tempuri.org/DajDS_IzUpita" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DajDS_SP">
      <soap:operation soapAction="http://tempuri.org/DajDS_SP" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DajScalarSTR_SP">
      <soap:operation soapAction="http://tempuri.org/DajScalarSTR_SP" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SP_ExecuteNonQuery">
      <soap:operation soapAction="http://tempuri.org/SP_ExecuteNonQuery" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje_SP">
      <soap:operation soapAction="http://tempuri.org/UpisPromenaBrisanje_SP" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje_IzUpita">
      <soap:operation soapAction="http://tempuri.org/UpisPromenaBrisanje_IzUpita" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje">
      <soap:operation soapAction="http://tempuri.org/UpisPromenaBrisanje" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpisVratiID">
      <soap:operation soapAction="http://tempuri.org/UpisVratiID" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ProveraFormataBrojaTelefona">
      <soap:operation soapAction="http://tempuri.org/ProveraFormataBrojaTelefona" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ProveraFormataBrojaTelefona_MinDuzina">
      <soap:operation soapAction="http://tempuri.org/ProveraFormataBrojaTelefona_MinDuzina" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IsValidEmailFormat">
      <soap:operation soapAction="http://tempuri.org/IsValidEmailFormat" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IsValidURL">
      <soap:operation soapAction="http://tempuri.org/IsValidURL" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IsValid_TekstPolje">
      <soap:operation soapAction="http://tempuri.org/IsValid_TekstPolje" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IsValidIPAddress">
      <soap:operation soapAction="http://tempuri.org/IsValidIPAddress" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Provera_Po_MOD11">
      <soap:operation soapAction="http://tempuri.org/Provera_Po_MOD11" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DajScalarSTR_IzUpita">
      <soap:operation soapAction="http://tempuri.org/DajScalarSTR_IzUpita" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQLvratiDT">
      <soap:operation soapAction="http://tempuri.org/IzvrsiSQLvratiDT" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQL">
      <soap:operation soapAction="http://tempuri.org/IzvrsiSQL" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQLVratiBrojSlogova">
      <soap:operation soapAction="http://tempuri.org/IzvrsiSQLVratiBrojSlogova" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ServiceSoap12" type="tns:ServiceSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="AutentifikacijaKorisnika_IzTabele_StoreProcedure">
      <soap12:operation soapAction="http://tempuri.org/AutentifikacijaKorisnika_IzTabele_StoreProcedure" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IzmenaLozinke_WebAPP">
      <soap12:operation soapAction="http://tempuri.org/IzmenaLozinke_WebAPP" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DajDS_IzUpita">
      <soap12:operation soapAction="http://tempuri.org/DajDS_IzUpita" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DajDS_SP">
      <soap12:operation soapAction="http://tempuri.org/DajDS_SP" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DajScalarSTR_SP">
      <soap12:operation soapAction="http://tempuri.org/DajScalarSTR_SP" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SP_ExecuteNonQuery">
      <soap12:operation soapAction="http://tempuri.org/SP_ExecuteNonQuery" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje_SP">
      <soap12:operation soapAction="http://tempuri.org/UpisPromenaBrisanje_SP" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje_IzUpita">
      <soap12:operation soapAction="http://tempuri.org/UpisPromenaBrisanje_IzUpita" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpisPromenaBrisanje">
      <soap12:operation soapAction="http://tempuri.org/UpisPromenaBrisanje" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UpisVratiID">
      <soap12:operation soapAction="http://tempuri.org/UpisVratiID" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ProveraFormataBrojaTelefona">
      <soap12:operation soapAction="http://tempuri.org/ProveraFormataBrojaTelefona" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ProveraFormataBrojaTelefona_MinDuzina">
      <soap12:operation soapAction="http://tempuri.org/ProveraFormataBrojaTelefona_MinDuzina" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IsValidEmailFormat">
      <soap12:operation soapAction="http://tempuri.org/IsValidEmailFormat" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IsValidURL">
      <soap12:operation soapAction="http://tempuri.org/IsValidURL" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IsValid_TekstPolje">
      <soap12:operation soapAction="http://tempuri.org/IsValid_TekstPolje" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IsValidIPAddress">
      <soap12:operation soapAction="http://tempuri.org/IsValidIPAddress" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Provera_Po_MOD11">
      <soap12:operation soapAction="http://tempuri.org/Provera_Po_MOD11" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="DajScalarSTR_IzUpita">
      <soap12:operation soapAction="http://tempuri.org/DajScalarSTR_IzUpita" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQLvratiDT">
      <soap12:operation soapAction="http://tempuri.org/IzvrsiSQLvratiDT" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQL">
      <soap12:operation soapAction="http://tempuri.org/IzvrsiSQL" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="IzvrsiSQLVratiBrojSlogova">
      <soap12:operation soapAction="http://tempuri.org/IzvrsiSQLVratiBrojSlogova" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service">
    <wsdl:port name="ServiceSoap" binding="tns:ServiceSoap">
      <soap:address location="http://10.1.6.20/Service.asmx" />
    </wsdl:port>
    <wsdl:port name="ServiceSoap12" binding="tns:ServiceSoap12">
      <soap12:address location="http://10.1.6.20/Service.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>