'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Istrazivanja.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property crtaaaaa() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("crtaaaaa", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property eyeBlue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("eyeBlue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property eyeOrange() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("eyeOrange", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IST1024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IST1024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IST10241() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IST10241", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IST1024T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IST1024T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IST32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IST32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IST768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IST768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IST768T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IST768T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IST768T1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IST768T1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property KonexyPersonalUse() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("KonexyPersonalUse", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property nowifi() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("nowifi", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PhoneW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PhoneW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to        0GDEFEbFŸ   ÖGPOSÊùµè à  âGSUB(áÇ œÄ  1¤LTSHž÷^´  7          '''?OS/2£2²W  ¸   `cmapÀÃf$  QŒ  $zcvt 1K  y   \fpgm‡ü$«  v  ¼gasp   ü   glyf&amp;èÜ   ®d ÄÌhdmxUŒ·Ÿ  DD          '''Hheadÿ?/Ÿ  &lt;   6hheaò•  t   $hmtx-¬ã    4êloca.D—Ì  yt  4ðmaxpm[  ˜    name€H s0  ¿postCáU: wð  	prep£)  wÄ  S      °Y{c_&lt;õ      Äð.    Ñ÷Ó*ø¿ýÕjs   	         býÕ  
        '''Áø¿ûÄ
        '''Î                       ''':           '''; ×  R          0   ˜ô   š3  š3  Ñ f            à 
        '''ÿP !   !    GOOG @  ÿýbýÕ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Roboto_Medium() As String
            Get
                Return ResourceManager.GetString("Roboto_Medium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Roboto_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Roboto_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VER3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VER3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property wifi() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("wifi", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
